{% set name = "perl-data-munge" %}
{% set version = "0.101" %}
{% set sha256 = "1021496a55b68dcb6d89516f2152b0766658e082f133f43d66e5a33cc1349579" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/M/MA/MAUKE/Data-Munge-0.101.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-base
    - perl-extutils-makemaker
    - perl-test-warnings
    - perl-exporter

  run:
    - perl
    - perl-base
    - perl-exporter

test:
  imports:
    - Data::Munge

about:
  home: http://metacpan.org/pod/Data::Munge
  license: perl_5
  summary: 'various utility functions'
