{% set name = "cgat-apps" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cgat/cgat-{{ version }}.tar.gz
  sha256: ba89a4208f8417e407a6ce967a0f186b42f89f105c6f892b08e11c385bb4aa74

  
build:
  number: 0
  run_exports:
    - {{ pin_subpackage('cgat-apps', max_pin="x.x") }}
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  entry_points:
    - cgat = cgat.cgat:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - pysam
    - htslib
    - ez_setup

  run:
    - python
    - cgatcore
    - alignlib-lite
    - biopython
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pandas') }}
    - pybedtools
    - pybigwig
    - pysam
    - htslib
    - pyyaml
    - quicksect
    - scipy
    - scikit-learn
    - sortedcontainers
    # Misc dependencies
    - bedtools
    - ucsc-bedgraphtobigwig
    - ucsc-wigtobigwig
    - coreutils
    - grep
    - zlib

test:
  imports:
    - cgat
  commands:
    - cgat --help
    - cgat --help Conversion
    - cgat gtf2table -h
    - cgat bam2bam -h
    - find ${PREFIX} -iname "*bamtools.cpython-*-x86_64-linux-gnu.so*" -exec ldd {} \;
    - cgat bam2bed -h

about:
  home: https://cgat-apps.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE
  summary: "Computational Genomics Analysis Toolkit"
