package:
  name: perl-cgi
  version: '4.64'

source:
  url: https://cpan.metacpan.org/authors/id/L/LE/LEEJO/CGI-4.64.tar.gz
  sha256: 39bd8e40ce00cdab39e0a2bc71abd2bbe451d1d97bc7e54e41a2e199eb6226e7

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
    - perl-extutils-makemaker
    - perl-file-temp
    - perl-parent
    - perl-test-warn
    - perl-exporter
    - perl-carp
    - perl-encode
    - perl-test-nowarnings
    - perl-base
    - perl-test-deep
    - perl-html-parser

  run:
    - perl
    - perl-file-temp
    - perl-exporter
    - perl-carp
    - perl-encode
    - perl-parent
    - perl-base
    - perl-html-parser
test:
  imports:
    - CGI
    - CGI::Carp
    - CGI::Cookie
    - CGI::File::Temp
    - CGI::HTML::Functions
    - CGI::Pretty
    - CGI::Push
    - CGI::Util

about:
  home: https://metacpan.org/pod/distribution/CGI/lib/CGI.pod
  license: GPL
  license_file: LICENSE
  summary: A generic file fetching mechanism
