{% set name = "metabolabpy" %}
{% set version = "0.9.26" %}
{% set sha256 = "87a44330f77b1a1d10ea664cd2023769bcf3547787a32a2868a4a2093a9b46ba" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/metabolabpy-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vvv
  entry_points:
    - metabolabpy = metabolabpy.__main__:main
  run_exports:
    - {{ pin_subpackage('metabolabpy', max_pin="x") }}

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - matplotlib-base
    - pandas
    - numba
    - scikit-learn
    - openpyxl
    - xlsxwriter
    - multiprocess
    - pybaselines
    - darkdetect
    - pygamma
    - pyside2
    - pyautogui
    - qtmodern

test:
  imports:
    - metabolabpy
  commands:
    - metabolabpy --help

about:
  home: https://github.com/ludwigc/metabolabpy
  summary: Python package for data processing of NMR 1D and 2D metabolomics and metabolism tracing data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RJMW
    - ludwigc
