{% set name = "fwdpy11" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fwdpy11-{{ version }}.tar.gz
  sha256: 7344ee59c4ca088ef011f18c7171e3c7376195ba0586302ef5991dcd1254fb7f

build:
  skip: True  # [py2k or py>=312]
  number: 0
  entry_points:
    - fwdpy11 = fwdpy11.__main__:main
  run_exports:
    - {{ pin_subpackage('fwdpy11', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - pip
    - setuptools-scm <8
    - pybind11 ==2.11.1
    - rust >=1.62.1
    - gsl
  run:
    - python
    - numpy >=1.20
    - tskit >=0.5
    - gsl
    - openblas
    - scipy
    - attrs
    - black
    - demes >=0.2
    - intervaltree
    - deprecated

test:
  imports:
    - fwdpy11
  commands:
    - fwdpy11 --help

about:
  home: https://github.com/molpopgen/fwdpy11
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: "COPYING"
  summary: 'Forward-time population genetic simulation in Python.'

extras:
  identifiers:
    - 10.1534/genetics.114.165019
    - 10.1371/journal.pcbi.1006581
