{% set version = "2.1.0" %}
{% set sha256_jar = "4f827642dadec816da6143e608e0e917c9f7eb1db383c4ae9281cde9a827f002" %}
{% set sha256_src = "389bca3dbb03f88931ec617b71bddfb3bba34c1c74707a4a40dddeb5451550c8" %}

package:
  name: hmftools-cuppa
  version: '{{ version }}'

source:
  - folder: jar
    url: https://github.com/hartwigmedical/hmftools/releases/download/cuppa-v{{ version }}/cuppa_v{{ version }}.jar
    sha256: '{{ sha256_jar }}'
  - folder: src
    url: https://github.com/hartwigmedical/hmftools/archive/refs/tags/cuppa-v{{ version }}.tar.gz
    sha256: '{{ sha256_src }}'

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage("hmftools-cuppa", max_pin="x.x") }}

requirements:
  run:
    - openjdk >=8
    - r-base >=4
    - r-cowplot
    - r-ggplot2
    - r-gridextra
    - r-stringi
    - r-tidyr
    - matplotlib-base >=3.3,<4
    - numpy >=1.19,<2
    - pandas >=1.1,<2
    - scipy >=1,<2
    - seaborn >=0.11,<1

test:
  commands:
    - 'cuppa | grep Cuppa'

about:
  home: https://github.com/hartwigmedical/hmftools/blob/master/cuppa/README.md
  license: GPL-3.0-only
  license_family: GPL3
  summary: Predict tissue of origin for tumor samples from WGTS data.
