{% set name = "aspera-cli" %}
{% set version = "4.16.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: https://github.com/IBM/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: e0079ddc9f57c5c9c38ddf2071ddef6954a9df2ef8a604ef85e6432d8b27b61b

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('aspera-cli', max_pin="x") }}

requirements:
  build:
    - ruby >=3
  host:
    - ruby >=3
  run:
    - ruby >=3

test:
  commands:
    - ascli -h
    - ascp -h

about:
  home: https://github.com/IBM/aspera-cli
  license: Apache-2.0
  license_file: 
    - LICENSE
    - aspera-license
  summary: "Command Line Interface for IBM Aspera products"
  dev_url: https://github.com/IBM/aspera-cli

extra:
  recipe-maintainers:
    - farchaab
