{% set version = "0.6.0" %}

package:
  name: dfast_qc
  version: {{ version }}

build:
  number: 0
  noarch: generic
source:
  url: https://github.com/nigyta/dfast_qc/archive/{{ version }}.tar.gz
  sha256: e202742dbc3dd16f9c8df938df157467fec1a4e7ef118df2834c0aab28b86736

requirements:


  run:
    - python >=3.8
    - prodigal
    - blast
    - fastani ==1.33
    - hmmer
    - checkm-genome ==1.2.2
    - ete3
    - more-itertools
    - peewee

test:
  commands:
    - which dfast_qc
    - dfast_qc -h

about:
  home: 'https://dfast.nig.ac.jp'
  license: "GPLv3"
  license_file: "docs/LICENSE"
  summary: "DFAST_QC: Taxonomy and completeness check for prokaryotic genomes"
  dev_url: "https://github.com/nigyta/dfast_qc"

