{% set name = "snapatac2" %}
{% set version = "2.6.0" %}
{% set sha256 = "9b44a3f1052635d5a6166df3a1b72b45ca218eea18e8d4bbb4a7b825aa1f7a61" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snapatac2-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv --no-build-isolation --no-deps
  run_exports:
    - {{ pin_subpackage('snapatac2', max_pin="x") }}

requirements:
  build:
    - make
    - cmake
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools-rust
    - maturin
  run:
    - python
    - anndata
    - scanpy
    - python-kaleido
    - multiprocess
    - macs3
    - natsort
    - numpy >=1.16.0
    - pandas >=1.0,<2.1.2
    - plotly >=5.6.0
    - polars >=0.20.0
    - pooch >=1.6.0
    - igraph >=0.10.3
    - pyarrow
    - pyfaidx >=0.7.0,<0.8.0
    - rustworkx
    - scipy >=1.4
    - scikit-learn >=1.0
    - tqdm >=4.62
    - typing_extensions

test:
  imports:
    - snapatac2

about:
  home: https://github.com/kaizhang/SnapATAC2
  summary: "Python/Rust package for single-cell epigenomics analysis"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://kzhang.org/SnapATAC2/
  dev_url: https://github.com/kaizhang/SnapATAC2

extra:
  identifiers:
    - biotools:snapatac
    - doi:10.1101/2023.09.11.557221
