{% set name = "pggb" %}
{% set version = "0.5.4" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://github.com/pangenome/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0f45e710e3a59225ae806db3686ecc32c59859671a8f1b7052259525dc6707f3

build:
  noarch: generic
  run_exports:
  - {{ pin_subpackage(name, max_pin='x.x') }}
  number: 0

requirements:
  run:
    - bc
    - tabix
    - gfaffix ==0.1.5b
    - gsl 2.7.0 
    - idna <3,>=2.5
    - multiqc ==1.21
    - odgi ==0.8.6
    - pigz
    - bcftools
    - seqwish ==0.7.10
    - smoothxg ==0.7.4
    - time
    - vg 1.40.0
    - wfmash ==0.13.0
    - python-igraph ==0.10.4

test:
  commands:
    - pggb --help

about:
  home: https://github.com/pangenome/pggb
  license: MIT
  license_file: LICENSE
  summary: This pangenome graph construction pipeline renders a collection of sequences into a pangenome graph (in the variation graph model).

extra:
  recipe-maintainers:
    - AndreaGuarracino
