{% set name = "iced" %}
{% set version = "0.5.13" %}
{% set sha256 = "455ecb3464cc64e0fdec776bc7b0f0cae9d729539be6865ac9d5436c5e77e6b9" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/iced-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  entry_points:
    - ice = iced.scripts.ice:main
  run_exports:
    - {{ pin_subpackage('iced', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
    - numpy
    - scipy >=0.13.3
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.3
    - pandas
    - scikit-learn
    - matplotlib-base

test:
  imports:
    - iced
  commands:
    - ice --help

about:
  home: https://github.com/hiclib/iced
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "The python module iced implements the ICE normalization of hic data."
