{% set version = "0.42.1" %}

package:
  name: rust-bio-tools
  version: {{ version }}

build:
  number: 0
  skip: True # [osx]

source:
  url: https://github.com/rust-bio/rust-bio-tools/archive/v{{ version }}.tar.gz
  sha256: c4759eb3eaec1d491b521172d1ace42feeef57cba0cd0ed0a4e413dcbde1b40f

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rust >=1.30
    - clangdev
    - pkg-config
    - make
    - cmake
  host:
    - gsl
    - libcblas
    - openssl
  run:
    - starcode

test:
  commands:
    - rbt --help

about:
  home: https://github.com/rust-bio/rust-bio-tools
  license: MIT
  summary: |
    A growing collection of fast and secure command line utilities for dealing with NGS data
    implemented on top of Rust-Bio.

extra:
  recipe-maintainers:
    - fxwiegand
    - felixmoelder
