{% set name = "perl-perl-version" %}
{% set version = "1.016" %}
{% set sha256 = "d23f4cb8fbb8d8c4c682c3bfac1a02b841e2a9cac71c0e84a6e32a0113365ad3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Perl-Version-1.016.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-pod-usage
    - perl-file-slurp-tiny
    - perl-extutils-makemaker
    - perl-getopt-long
    - perl-data-dumper
    - perl-carp

  run:
    - perl
    - perl-carp
    - perl-file-slurp-tiny
    - perl-getopt-long
    - perl-data-dumper
    - perl-pod-usage

test:
  imports:
    - Perl::Version

about:
  home: http://metacpan.org/pod/Perl::Version
  license: perl_5
  summary: 'Parse and manipulate Perl version strings'
