{% set version = "2024.03.08" %}

package:
  name: bacpage
  version: {{ version }}

source:
  url: https://github.com/CholGen/bacpage/archive/refs/tags/{{ version }}.tar.gz
  sha256: a0344f0e6c218a2e9a54a3d63eecc143c5d05ad3b0c4bf4379e34369b6ee53a7 

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
  run_exports:
    - {{ pin_subpackage('bacpage') }}

requirements:
  host:
    - python <3.12,>=3.9
    - pip
  run:
    - python <3.12,>=3.9
    - bc
    - bcftools =1.17
    - bedtools
    - biopython
    - bwa
    - emboss
    - fastqc
    - iqtree
    - multiqc
    - pandas
    - qualimap
    - samtools =1.17
    - snakemake-minimal
    - snp-sites
    - fastp
    - lighter
    - flash
    - unicycler
    - prokka
    - quast
    - abricate

test:
  commands:
    - bacpage -h
    - bacpage version
    - bacpage example "$(mktemp -d)"

about:
  home: https://github.com/CholGen/bacpage
  license: "GPL-3.0-or-later"
  license_file: LICENSE
  summary: An easy-to-use pipeline for the assembly and analysis of bacterial genomes
  

extra:
  recipe-maintainers:
    - watronfire
