{% set name = "ntedit" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

source:
  url: https://github.com/bcgsc/ntEdit/archive/v{{ version }}.tar.gz
  sha256: 91264e2c1215ddbe37e7c1eee6181f19251623c9f0bc1a3025a1d900488e5a92

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - automake
    - autoconf
    - perl

  host:
    - zlib
  run:
    - llvm-openmp # [osx]
    - zlib
    - ntHits ==0.0.1

test:
  commands:
    - ntedit --help

about:
  home: https://github.com/bcgsc/ntEdit
  license: GPL-3.0
  license_file: LICENSE
  summary: 'ultra fast, scalable genome assembly polishing and snv detection'
