package:
  name: perl-spreadsheet-parseexcel
  version: "0.66"

source:
  url: https://cpan.metacpan.org/authors/id/J/JM/JMCNAMARA/Spreadsheet-ParseExcel-0.66.tar.gz
  sha256: bfd76acfba988601dc051bda73b4bb25f6839a006dd960b6a7401c249245f65b

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-crypt-rc4
    - perl-digest-perl-md5
    - perl-io-stringy
    - perl-ole-storage_lite
    - perl-jcode
    - perl-spreadsheet-writeexcel
    - perl-unicode-map

  run:
    - perl
    - perl-crypt-rc4
    - perl-digest-perl-md5
    - perl-io-stringy
    - perl-ole-storage_lite
    - perl-jcode
    - perl-spreadsheet-writeexcel
    - perl-unicode-map

test:
  # Perl 'use' tests
  imports:
    - Spreadsheet::ParseExcel
    - Spreadsheet::ParseExcel::Cell
    - Spreadsheet::ParseExcel::Dump
    - Spreadsheet::ParseExcel::FmtDefault
    - Spreadsheet::ParseExcel::FmtJapan
    - Spreadsheet::ParseExcel::FmtJapan2
    - Spreadsheet::ParseExcel::FmtUnicode
    - Spreadsheet::ParseExcel::Font
    - Spreadsheet::ParseExcel::Format
    - Spreadsheet::ParseExcel::SaveParser
    - Spreadsheet::ParseExcel::SaveParser::Workbook
    - Spreadsheet::ParseExcel::SaveParser::Worksheet
    - Spreadsheet::ParseExcel::Utility
    - Spreadsheet::ParseExcel::Workbook
    - Spreadsheet::ParseExcel::Worksheet

about:
  home: http://github.com/runrig/spreadsheet-parseexcel/
  license: perl_5
  summary: 'Read information from an Excel file.'
