{% set name = "funannotate" %}
{% set version = "1.8.17" %}

package:
  name: funannotate
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/funannotate/funannotate-{{ version }}.tar.gz
  sha256: bdadfd7a5636383c1c40c26dab37c5908a77e8c4064adced84f1ba9e86187a04

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  entry_points:
    - funannotate=funannotate.funannotate:main
  run_exports:
    - {{ pin_subpackage('funannotate', max_pin="x") }}

requirements:
  host:
    - pip
    - python >=3.6,<3.10
  run:
    - python >=3.6,<3.10
    - biopython <1.80
    - goatools
    - matplotlib-base <3.5
    - natsort
    - numpy
    - pandas
    - psutil
    - requests
    - scikit-learn
    - scipy
    - seaborn
    - blast
    - tantan
    - bedtools
    - hmmer
    - exonerate
    - diamond >=2.1.6
    - tbl2asn
    - ucsc-pslcdnafilter
    - pasa >=2.5.3
    - trimmomatic
    - raxml
    - trimal
    - mafft >=7
    - iqtree
    - kallisto >=0.46.0,<0.46.2
    - minimap2
    - evidencemodeler
    - codingquarry
    - stringtie
    - snap
    - glimmerhmm
    - bamtools
    - augustus >=3.5.0
    - trinity >=2.15.1
    - trnascan-se
    - hisat2
    - proteinortho >=6.0.16
    - salmon >=0.9
    - phyml
    - perl
    - perl-math-utils  # Needed by GeneMark
    - perl-mce  # Needed by GeneMark
    - perl-dbd-mysql
    - perl-clone
    - perl-hash-merge
    - perl-soap-lite
    - perl-json
    - perl-logger-simple
    - perl-scalar-util-numeric
    - perl-text-soundex
    - perl-parallel-forkmanager
    - perl-db-file
    - perl-local-lib
    - r-base >=3.4.1
    - ete3
    - distro
    - samtools >=1.9
    - pigz

test:
  commands:
    - "funannotate --help | grep \"Funannotate is a genome prediction\""

about:
  home: "https://github.com/nextgenusfs/funannotate"
  license: "BSD-2-Clause"
  license_family: "BSD"
  license_file: "LICENSE.md"
  summary: "funannotate: eukaryotic genome annotation pipeline"
  doc_url: "https://funannotate.readthedocs.io/en/latest/"
  dev_url: "https://github.com/nextgenusfs/funannotate"

extra:
  recipe-maintainers:
    - nextgenusfs
  identifiers:
    - biotools:funannotate
    - usegalaxy-eu:funannotate_compare
    - usegalaxy-eu:funannotate_clean
    - usegalaxy-eu:funannotate_predict
    - usegalaxy-eu:funannotate_annotate
