{% set name = "perl-datetime-locale" %}
{% set version = "1.41" %}
{% set sha256 = "d928902b13262c998ac06c0a7f9911cc869014a0db2e72d2138fa5ab3c10dac2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Locale-1.41.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - perl-cpan-meta-check
    - perl-test-requires
    - perl-test-warnings
    - perl-extutils-makemaker
    - perl-specio
    - perl-params-validationcompiler
    - perl-test-more
    - perl-namespace-autoclean
    - perl-dist-checkconflicts
    - perl-file-sharedir-install
    - perl-file-sharedir
    - perl-test2-plugin-nowarnings
  run:
    - perl
    - perl-namespace-autoclean
    - perl-dist-checkconflicts
    - perl-params-validationcompiler
    - perl-specio
    - perl-file-sharedir

test:
  imports:
    - DateTime::Locale
    - DateTime::Locale::Base
    - DateTime::Locale::Catalog
    - DateTime::Locale::Data
    - DateTime::Locale::FromData
    - DateTime::Locale::Util

about:
  home: http://metacpan.org/release/DateTime-Locale
  license: perl_5
  summary: 'Localization support for DateTime.pm'
