{% set name = "dysgu" %}
{% set version = "1.6.3" %}
{% set sha256hash = "874ec90a965a4f5eb8875a09510830739bc963c1aaa7d91848e271f9c6af1176" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kcleal/dysgu/archive/v{{ version }}.tar.gz
  sha256: {{ sha256hash }}

build:
  number: 0
  skip: True  # [py < 37]
  entry_points:
    - dysgu = dysgu.main:cli
  run_exports:
    - {{ pin_subpackage('dysgu', max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - htslib >=1.12
    - numpy >=1.18
    - lightgbm
    - zlib
    - pysam >=0.19
    - libcurl
    - openssl
    - bzip2
    - xz
    - scipy >=1.7
    - pandas >=1.2
    - networkx >=2.4
    - scikit-learn >=0.22
    - python-edlib
    - sortedcontainers
    - click >=8.0
  run:
    - python
    - numpy >=1.18
    - scipy >1.7
    - pandas >=1.2
    - networkx >=2.4
    - scikit-learn >=0.22
    - python-edlib
    - sortedcontainers
    - lightgbm
    - zlib
    - click >=8.0
    - pysam >=0.19
    - libcurl
    - openssl
    - bzip2
    - xz
    - htslib >=1.12
    - cython

test:
  requires:
    - cython
  imports:
    - dysgu
  files:
    - dysgu/tests/*
  commands:
    - 'dysgu --help'

about:
  home: https://github.com/kcleal/dysgu
  summary: A collection of tools for calling structural variants using short or long reads
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/kcleal/dysgu

extra:
  container:
      extended-base: True
  recipe-maintainers:
    - kcleal
  skip-lints:
    - cython_must_be_in_host
