{% set name = "ngs-smap" %}
{% set version = "5.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 713bc0c393ac26fc208d0c316a3141fb1be96fab2a69057c872229ebf56ef3d8
  patches:
    - patch

build:
  number: 0
  noarch: python
  entry_points:
    - smap = smap.__main__:main
  ignore_prefix_files: True
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv"
  run_exports:
    - {{ pin_subpackage('ngs-smap', max_pin="x") }}

requirements:
  host:
    - setuptools-scm
    - setuptools_scm_git_archive
    - python >=3.8.1
  run:
    - pybedtools >=0.9.0,<0.10
    - pysam >=0.18.0,<0.19
    - pandas >=1.4.0,<1.5
    - matplotlib-base >=3.5.1,<3.6
    - colorlog >=6.6.0,<6.7
    - python >=3.8.1

test:
  commands:
    - smap compare --help

about:
  home: "https://gitlab.com/truttink/smap"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "SMAP is an analysis tool for stack-based NGS read mapping"

extra:
  recipe-maintainers:
    - ieguinoa
