{% set version = "24.0.0" %}
{% set sha256 = "4341a5bcbc336b27f55ef50735aa37d60bb1ba8621a258db73805cda3b5b87c3" %}
{% set galaxy_version = version.split(".")[:2]|join(".") %}

package:
  name: galaxy-data
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/galaxy-data/galaxy-data-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  run_exports:
    - {{ pin_subpackage("galaxy-data", max_pin="x") }}

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - galaxy-files >={{ galaxy_version }}
    - galaxy-objectstore >={{ galaxy_version }}
    - galaxy-util >={{ galaxy_version }}
    - galaxy_sequence_utils
    - alembic
    - bdbag
    - bx-python
    - h5py
    - isa-rwval
    - markupsafe
    - mrcfile
    - numpy
    - parsley
    - pycryptodome
    - pydantic
    # missing - pylibmagici
    - python-magic
    - pysam >=0.20
    - rocrate
    - social-auth-core
    - sqlalchemy
    - sqlalchemy-migrate
    - sqlalchemy-utils
    - tifffile
    - typing-extensions
    - WebOb
    - python >=3.7
    # extra: jstree
    # - dictobj
    # extra: template
    # - future
    # - cheetah3

test:
  imports:
    - galaxy
    - galaxy.exceptions
    - galaxy.model
    - galaxy.datatypes.dataproviders
    - galaxy.quota
    - galaxy.security

about:
  home: https://galaxyproject.org
  license: AFL-3.0
  license_file: LICENSE
  summary: The Galaxy models, datatype framework, and datatype implementations.
  doc_url: https://docs.galaxyproject.org
  dev_url: https://github.com/galaxyproject/galaxy

extra:
  identifiers:
    - biotools:galaxy
    - doi:10.1093/nar/gky379
  recipe-maintainers:
    - bernt-matthias
