{% set version = "0.9.2" %}

package:
  name: tower-cli
  version: {{ version }}

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("tower-cli", max_pin="x.x") }}
    
source:
  - url: https://github.com/seqeralabs/tower-cli/releases/download/v{{ version }}/tw-linux-x86_64 # [linux]
    sha256: 1b96696219d922aaa1a5e09f4a018b34c38806c134234b7f9bde19c92f04ab64 # [linux]
    fn: tw # [linux]
  - url: https://github.com/seqeralabs/tower-cli/releases/download/v{{ version }}/tw-osx-x86_64 # [osx]
    sha256: e96c036401c21b4c9b0379a4099192161d94f7567ea16313e7147d6f75828394 # [osx] 
    fn: tw # [osx]
  - url: https://github.com/seqeralabs/tower-cli/releases/download/v{{ version }}/tw-osx-arm64 # [arm64]
    sha256: 31ffa200aea3e70533222cab08a212080b889d933ac7ee2b8ece22c51d3e8c1a # [arm64]
    fn: tw # [arm64]
  - url: https://github.com/seqeralabs/tower-cli/releases/download/{{ version }}/tw-windows-x86_64.exe # [win]
    sha256: c51f2f9b146f4d4d074770e5eb8684188a7358aa61032f1822a0e7d681a4f05c # [win]
    fn: tw # [win]

requirements:
  run:
    - openjdk >=17

test:
  commands:
    - tw --help

about:
  home: "https://github.com/seqeralabs/tower-cli"
  license: "MPL-2.0"
  summary: "The Tower CLI an interface to Nextflow Tower via the CLI"
extra:
  skip-lints:
    - should_be_noarch_generic
    - should_not_use_fn
