name: Bulk branch
on:
  push:
    branches:
      - bulk
jobs:
  build-linux:
    name: Bulk Linux Builds
    if: "contains(github.event.head_commit.message, '[ci run]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        runner: [0]
    steps:
      - uses: actions/checkout@v3
      
      - name: set git user
        run: |
          git config user.name BiocondaBot
          git config user.email BiocondaBot@users.noreply.github.com

      - name: set path
        run: echo "/opt/mambaforge/bin" >> $GITHUB_PATH

      - name: Fetch conda install script
        run: |
          wget https://raw.githubusercontent.com/bioconda/bioconda-common/bulk/{common,install-and-set-up-conda,configure-conda}.sh

      - name: Restore cache
        id: cache
        uses: actions/cache@v3
        with:
          path: /opt/mambaforge
          key: ${{ runner.os }}--bulk--${{ hashFiles('install-and-set-up-conda.sh', 'common.sh', 'configure-conda.sh') }}

      - name: Set up bioconda-utils
        if: steps.cache.outputs.cache-hit != 'true'
        run: bash install-and-set-up-conda.sh

      # This script can be used to reconfigure conda to use the right channel setup.
      # This has to be done after the cache is restored, because
      # the channel setup is not cached as it resides in the home directory.
      # We could use a system-wide (and therefore cached) channel setup,
      # but mamba does not support that at the time of implementation
      # (it ignores settings made with --system).
      - name: Configure conda
        run: bash configure-conda.sh

      - name: Install dev version of bioconda-utils for testing https://github.com/bioconda/bioconda-utils/pull/945
        run: |
          source /opt/mambaforge/etc/profile.d/conda.sh
          source /opt/mambaforge/etc/profile.d/mamba.sh
          mamba activate bioconda
          pip install git+https://github.com/bioconda/bioconda-utils.git@b7e56f56ac2f4ba1b64a7a692d7c40d839fe170f

      - name: Build and upload
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          INVOLUCRO_AUTH: ${{ secrets.INVOLUCRO_AUTH }}
          QUAY_OAUTH_TOKEN: ${{ secrets.QUAY_OAUTH_TOKEN }}
          # Mimic circleci
          OSTYPE: "linux-gnu"
          CI: "true"
        run: |
          set -e
          eval "$(conda shell.bash hook)"
          conda activate bioconda
          echo '============'
          conda info --all
          conda config --show-sources
          python -c 'import bioconda_utils.utils as u ; import pathlib as p ; print(*(f"{f}:\n{p.Path(f).read_text()}" for f in u.load_conda_build_config().exclusive_config_files), sep="\n")'
          echo '============'
          bioconda-utils build recipes config.yml \
            --packages bioconductor-bsgenome bioconductor-bsgenome.alyrata.jgi.v1 bioconductor-bsgenome.amellifera.beebase.assembly4 bioconductor-bsgenome.amellifera.ncbi.amelhav3.1 bioconductor-bsgenome.amellifera.ucsc.apimel2 bioconductor-bsgenome.amellifera.ucsc.apimel2.masked bioconductor-bsgenome.aofficinalis.ncbi.v1 bioconductor-bsgenome.athaliana.tair.04232008 bioconductor-bsgenome.athaliana.tair.tair9 bioconductor-bsgenome.btaurus.ucsc.bostau3 bioconductor-bsgenome.btaurus.ucsc.bostau3.masked bioconductor-bsgenome.btaurus.ucsc.bostau4 bioconductor-bsgenome.btaurus.ucsc.bostau4.masked bioconductor-bsgenome.btaurus.ucsc.bostau6 bioconductor-bsgenome.btaurus.ucsc.bostau6.masked bioconductor-bsgenome.btaurus.ucsc.bostau8 bioconductor-bsgenome.btaurus.ucsc.bostau9 bioconductor-bsgenome.btaurus.ucsc.bostau9.masked bioconductor-bsgenome.carietinum.ncbi.v1 bioconductor-bsgenome.celegans.ucsc.ce10 bioconductor-bsgenome.celegans.ucsc.ce11 bioconductor-bsgenome.celegans.ucsc.ce2 bioconductor-bsgenome.celegans.ucsc.ce6 bioconductor-bsgenome.cfamiliaris.ucsc.canfam2 bioconductor-bsgenome.cfamiliaris.ucsc.canfam2.masked bioconductor-bsgenome.cfamiliaris.ucsc.canfam3 bioconductor-bsgenome.cfamiliaris.ucsc.canfam3.masked bioconductor-bsgenome.cjacchus.ucsc.caljac3 bioconductor-bsgenome.cjacchus.ucsc.caljac4 bioconductor-bsgenome.cneoformansvargrubiikn99.ncbi.asm221672v1 bioconductor-bsgenome.creinhardtii.jgi.v5.6 bioconductor-bsgenome.dmelanogaster.ucsc.dm2 bioconductor-bsgenome.dmelanogaster.ucsc.dm2.masked bioconductor-bsgenome.dmelanogaster.ucsc.dm3 bioconductor-bsgenome.dmelanogaster.ucsc.dm3.masked bioconductor-bsgenome.dmelanogaster.ucsc.dm6 bioconductor-bsgenome.drerio.ucsc.danrer10 bioconductor-bsgenome.drerio.ucsc.danrer11 bioconductor-bsgenome.drerio.ucsc.danrer5 bioconductor-bsgenome.drerio.ucsc.danrer5.masked bioconductor-bsgenome.drerio.ucsc.danrer6 bioconductor-bsgenome.drerio.ucsc.danrer6.masked bioconductor-bsgenome.drerio.ucsc.danrer7 bioconductor-bsgenome.drerio.ucsc.danrer7.masked bioconductor-bsgenome.dvirilis.ensembl.dvircaf1 bioconductor-bsgenome.ecoli.ncbi.20080805 bioconductor-bsgenome.gaculeatus.ucsc.gasacu1 bioconductor-bsgenome.gaculeatus.ucsc.gasacu1.masked bioconductor-bsgenome.ggallus.ucsc.galgal3 bioconductor-bsgenome.ggallus.ucsc.galgal3.masked bioconductor-bsgenome.ggallus.ucsc.galgal4 bioconductor-bsgenome.ggallus.ucsc.galgal4.masked bioconductor-bsgenome.ggallus.ucsc.galgal5 bioconductor-bsgenome.ggallus.ucsc.galgal6 bioconductor-bsgenome.gmax.ncbi.gmv40 bioconductor-bsgenome.hsapiens.1000genomes.hs37d5 bioconductor-bsgenome.hsapiens.ncbi.grch38 bioconductor-bsgenome.hsapiens.ncbi.t2t.chm13v2.0 bioconductor-bsgenome.hsapiens.ucsc.hg17 bioconductor-bsgenome.hsapiens.ucsc.hg17.masked bioconductor-bsgenome.hsapiens.ucsc.hg18 bioconductor-bsgenome.hsapiens.ucsc.hg18.masked bioconductor-bsgenome.hsapiens.ucsc.hg19 bioconductor-bsgenome.hsapiens.ucsc.hg19.masked bioconductor-bsgenome.hsapiens.ucsc.hg38 bioconductor-bsgenome.hsapiens.ucsc.hg38.dbsnp151.major bioconductor-bsgenome.hsapiens.ucsc.hg38.dbsnp151.minor bioconductor-bsgenome.hsapiens.ucsc.hg38.masked bioconductor-bsgenome.hsapiens.ucsc.hs1 bioconductor-bsgenome.mdomestica.ucsc.mondom5 bioconductor-bsgenome.mfascicularis.ncbi.5.0 bioconductor-bsgenome.mfascicularis.ncbi.6.0 bioconductor-bsgenome.mfuro.ucsc.musfur1 bioconductor-bsgenome.mmulatta.ucsc.rhemac10 bioconductor-bsgenome.mmulatta.ucsc.rhemac2 bioconductor-bsgenome.mmulatta.ucsc.rhemac2.masked bioconductor-bsgenome.mmulatta.ucsc.rhemac3 bioconductor-bsgenome.mmulatta.ucsc.rhemac3.masked bioconductor-bsgenome.mmulatta.ucsc.rhemac8 bioconductor-bsgenome.mmusculus.ucsc.mm10 bioconductor-bsgenome.mmusculus.ucsc.mm10.masked bioconductor-bsgenome.mmusculus.ucsc.mm39 bioconductor-bsgenome.mmusculus.ucsc.mm8 bioconductor-bsgenome.mmusculus.ucsc.mm8.masked bioconductor-bsgenome.mmusculus.ucsc.mm9 bioconductor-bsgenome.mmusculus.ucsc.mm9.masked bioconductor-bsgenome.osativa.msu.msu7 bioconductor-bsgenome.ppaniscus.ucsc.panpan1 bioconductor-bsgenome.ppaniscus.ucsc.panpan2 bioconductor-bsgenome.ptroglodytes.ucsc.pantro2 bioconductor-bsgenome.ptroglodytes.ucsc.pantro2.masked bioconductor-bsgenome.ptroglodytes.ucsc.pantro3 bioconductor-bsgenome.ptroglodytes.ucsc.pantro3.masked bioconductor-bsgenome.ptroglodytes.ucsc.pantro5 bioconductor-bsgenome.ptroglodytes.ucsc.pantro6 bioconductor-bsgenome.rnorvegicus.ucsc.rn4 bioconductor-bsgenome.rnorvegicus.ucsc.rn4.masked bioconductor-bsgenome.rnorvegicus.ucsc.rn5 bioconductor-bsgenome.rnorvegicus.ucsc.rn5.masked bioconductor-bsgenome.rnorvegicus.ucsc.rn6 bioconductor-bsgenome.rnorvegicus.ucsc.rn7 bioconductor-bsgenome.scerevisiae.ucsc.saccer1 bioconductor-bsgenome.scerevisiae.ucsc.saccer2 bioconductor-bsgenome.scerevisiae.ucsc.saccer3 bioconductor-bsgenome.sscrofa.ucsc.susscr11 bioconductor-bsgenome.sscrofa.ucsc.susscr3 bioconductor-bsgenome.sscrofa.ucsc.susscr3.masked bioconductor-bsgenome.tgondii.toxodb.7.0 bioconductor-bsgenome.tguttata.ucsc.taegut1 bioconductor-bsgenome.tguttata.ucsc.taegut1.masked bioconductor-bsgenome.tguttata.ucsc.taegut2 bioconductor-bsgenome.vvinifera.urgi.iggp12xv0 bioconductor-bsgenome.vvinifera.urgi.iggp12xv2 bioconductor-bsgenome.vvinifera.urgi.iggp8x bioconductor-bsgenomeforge \
            --docker --mulled-test --anaconda-upload --mulled-upload-target biocontainers \
            --lint --skiplist-leafs
          conda clean -y --all

  build-osx:
    name: Bulk OSX Builds
    if: "contains(github.event.head_commit.message, '[ci run]')"
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        runner: [0]
    steps:
      - uses: actions/checkout@v3
      
      - name: set git user
        run: |
          git config user.name BiocondaBot
          git config user.email BiocondaBot@users.noreply.github.com

      - name: set path
        run: echo "/opt/mambaforge/bin" >> $GITHUB_PATH

      - name: Fetch conda install script
        run: |
          wget https://raw.githubusercontent.com/bioconda/bioconda-common/bulk/{common,install-and-set-up-conda,configure-conda}.sh

      - name: Restore cache
        id: cache
        uses: actions/cache@v3
        with:
          path: /opt/mambaforge
          key: ${{ runner.os }}--bulk--${{ hashFiles('install-and-set-up-conda.sh', 'common.sh', 'configure-conda.sh') }}

      - name: Set up bioconda-utils
        if: steps.cache.outputs.cache-hit != 'true'
        run: bash install-and-set-up-conda.sh

      # This script can be used to reconfigure conda to use the right channel setup.
      # This has to be done after the cache is restored, because
      # the channel setup is not cached as it resides in the home directory.
      # We could use a system-wide (and therefore cached) channel setup,
      # but mamba does not support that at the time of implementation
      # (it ignores settings made with --system).
      - name: Configure conda
        run: bash configure-conda.sh

      - name: Install dev version of bioconda-utils for testing https://github.com/bioconda/bioconda-utils/pull/945
        run: |
          source /opt/mambaforge/etc/profile.d/conda.sh
          source /opt/mambaforge/etc/profile.d/mamba.sh
          mamba activate bioconda
          pip install git+https://github.com/bioconda/bioconda-utils.git@b7e56f56ac2f4ba1b64a7a692d7c40d839fe170f

      - name: Build and upload
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          INVOLUCRO_AUTH: ${{ secrets.INVOLUCRO_AUTH }}
          QUAY_OAUTH_TOKEN: ${{ secrets.QUAY_OAUTH_TOKEN }}
          # Mimic circleci
          OSTYPE: "darwin"
          CI: "true"
        run: |
          set -e
          eval "$(conda shell.bash hook)"
          conda activate bioconda

          # The SDK isn't actually cached, so reinstall it
          run_conda_forge_build_setup

          echo '============'
          conda info --all
          conda config --show-sources
          conda activate bioconda
          python -c 'import bioconda_utils.utils as u ; import pathlib as p ; print(*(f"{f}:\n{p.Path(f).read_text()}" for f in u.load_conda_build_config().exclusive_config_files), sep="\n")'
          echo '============'
          bioconda-utils build recipes config.yml \
            --packages bioconductor-vanillaice \
            --lint --anaconda-upload --skiplist-leafs
          conda clean -y --all
